version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build step completed. No actual build for now.
  post_build:
    commands:
      - echo Deploying to EC2...
      - scp -o StrictHostKeyChecking=no -i nodeapp.pem -r * ec2-user@3.236.87.54:/var/www/ec2app/
      - echo Restarting Node.js app...
      - ssh -o StrictHostKeyChecking=no -i nodeapp.pem ec2-user@3.236.87.54 "pm2 restart all"

